### ISSUE TITLE
scrapy_zyte_smartproxy in version 2.2.0 issue with request

### ISSUE THREAD

**Issue by donahcandia0121** [scrapy-plugins/scrapy-zyte-smartproxy#105]
When deploying to our server with scrapy_zyte_smartproxy version 2.2.0 encountered an issue when trying to do a request and it keeps on retrying until it gave up. 

What I did was downgrade to version 2.1.0 and it all works again.

Can you check on this, please?

Thank you.

**Comment by Gallaecio** [comment]
Which version of Scrapy was this server using? Also, is the issue reproducible with https://github.com/scrapy/scrapy/pull/5626 ?

**Comment by Gallaecio** [comment]
Closing due to a lack of feedback.
